#ifndef BEET_MAINTENANCE_TLV_H
#define BEET_MAINTENANCE_TLV_H

#include <stdint.h>

#define BEET_MAINTENANCE_METADATA_MAGIC 0x544D5442UL
#define BEET_MAINTENANCE_METADATA_FORMAT_VERSION 1U

typedef enum {
    BEET_MAINTENANCE_TLV_PRODUCT_ID = 0x0001,
    BEET_MAINTENANCE_TLV_HARDWARE_REV = 0x0002,
    BEET_MAINTENANCE_TLV_FIRMWARE_VERSION = 0x0003,
    BEET_MAINTENANCE_TLV_BUILD_LABEL = 0x0004,
    BEET_MAINTENANCE_TLV_MAINTENANCE_PROTOCOL_VERSION = 0x0005,
    BEET_MAINTENANCE_TLV_RUNTIME_PROTOCOL_VERSION = 0x0006,
    BEET_MAINTENANCE_TLV_IMAGE_KIND = 0x0007,
    BEET_MAINTENANCE_TLV_COMPATIBLE_HARDWARE_REV = 0x0008,
} beet_maintenance_tlv_type_t;

#endif
