idf_component_register(
    SRCS
        "src/beet_board.c"
        "src/beet_ble.c"
        "src/beet_ble_codec.c"
        "src/beet_controller.c"
        "src/beet_core.c"
        "src/beet_event_ring.c"
        "src/beet_iface_names.c"
        "src/beet_storage.c"
    INCLUDE_DIRS "include"
    REQUIRES
        esp_adc
        esp_driver_i2c
        esp_lcd
        bt
        esp_app_format
        esp_driver_gpio
        esp_partition
        esp_rom
        esp_timer
        espressif__led_strip
        nvs_flash
)
