package de.aarondietz.beetmeister

import de.aarondietz.beetmeister.R
import de.aarondietz.beetmeister.strings.BeetStringResolver
import java.util.Locale

internal class TestBeetStringResolver : BeetStringResolver {
    override val locale: Locale = Locale.US

    override fun get(id: Int, vararg args: Any): String {
        val template = when (id) {
            R.string.placeholder_dash -> "-"
            R.string.common_none -> "None"
            R.string.common_yes -> "Yes"
            R.string.common_no -> "No"
            R.string.common_time_range -> "%1\$s - %2\$s"
            R.string.common_today -> "Today"
            R.string.common_yesterday -> "Yesterday"
            R.string.common_unknown -> "Unknown"
            R.string.common_unknown_with_code -> "Unknown (%1\$s)"
            R.string.common_millivolts -> "%1\$d mV"
            R.string.events_pending_time_sync -> "Pending time sync"
            R.string.events_ignored_legacy -> "Ignored legacy"
            R.string.events_boot_section_title -> "Boot %1\$d"
            R.string.events_relative_uptime -> "t+%1\$s"
            R.string.events_filter_system -> "System"
            R.string.events_filter_bluetooth -> "Bluetooth"
            R.string.events_filter_sleep -> "Sleep"
            R.string.events_filter_startup -> "Startup"
            R.string.events_filter_mqtt -> "MQTT"
            R.string.events_filter_ota -> "OTA"
            R.string.events_disconnected_reason -> "Disconnected"
            R.string.events_disconnect_code -> "Disconnect code %1\$d"
            R.string.events_bond_status -> "Bond status %1\$d"
            R.string.events_publish_failed -> "Publish failed"
            R.string.events_publish_status -> "Publish status %1\$d"
            R.string.events_known_peer -> "Known peer"
            R.string.events_new_peer -> "New peer"
            R.string.events_known_peer_address -> "Known %1\$s"
            R.string.events_new_peer_address -> "New %1\$s"
            R.string.format_duration_hours_minutes -> "%1\$dh %2\$dm"
            R.string.format_duration_minutes_seconds -> "%1\$dm %2\$ds"
            R.string.format_duration_seconds_only -> "%1\$ds"
            R.string.system_event_startup -> "Startup"
            R.string.system_event_sleep -> "Sleep"
            R.string.system_event_ble_connect -> "Bluetooth connected"
            R.string.system_event_ble_disconnect -> "Bluetooth disconnected"
            R.string.system_event_ble_bond_success -> "Bluetooth bonded"
            R.string.system_event_ble_bond_failed -> "Bluetooth bond failed"
            R.string.system_event_ble_bonds_cleared -> "Bluetooth bonds cleared"
            R.string.system_event_valve_opened -> "Valve opened"
            R.string.system_event_valve_closed -> "Valve closed"
            R.string.system_event_mqtt_connect -> "MQTT connected"
            R.string.system_event_mqtt_disconnect -> "MQTT disconnected"
            R.string.system_event_mqtt_publish_failed -> "MQTT publish failed"
            R.string.system_event_ota_started -> "OTA started"
            R.string.system_event_ota_failed -> "OTA failed"
            R.string.system_event_ota_ready -> "OTA ready"
            R.string.stop_reason_completed -> "Completed"
            R.string.stop_reason_manual_stop -> "Manual stop"
            R.string.stop_reason_low_battery_abort -> "Low battery abort"
            R.string.stop_reason_sensor_sanity_failure -> "Sanity failure"
            R.string.stop_reason_sensor_invalid_abort -> "Sensor invalid abort"
            R.string.stop_reason_system_abort -> "System abort"
            R.string.stop_reason_idle_low_power_sleep -> "Idle low-power sleep"
            R.string.stop_reason_deep_low_battery_sleep -> "Deep low-battery sleep"
            R.string.block_reason_code_none -> "None"
            R.string.block_reason_code_moisture_response_test_failed -> "Moisture response test failed"
            R.string.block_reason_code_sensor_reading_invalid -> "Sensor reading invalid"
            R.string.block_reason_code_low_battery_abort -> "Low battery abort"
            R.string.trigger_source_automatic -> "Automatic"
            R.string.trigger_source_manual -> "Manual"
            R.string.trigger_source_test -> "Moisture test"
            R.string.trigger_source_none -> "None"
            R.string.command_message_bonds_cleared -> "Bluetooth bonds cleared."
            R.string.command_message_no_bonds -> "No Bluetooth bonds to clear."
            R.string.command_message_rebooting -> "Controller is rebooting."
            R.string.command_message_factory_reset_started -> "Factory reset started. The controller will reboot and must be paired again."
            R.string.command_message_pair_prefix -> "Pair %1\$d: %2\$s."
            R.string.command_reason_bonds_cleared -> "Bluetooth bonds cleared"
            R.string.command_reason_no_bonds -> "No Bluetooth bonds to clear"
            R.string.command_reason_busy -> "Controller is busy"
            R.string.command_reason_rate_limited -> "Too many commands; try again"
            R.string.command_reason_rebooting -> "Controller is rebooting"
            R.string.command_reason_factory_reset_started -> "Factory reset started"
            else -> error("Missing test string resource id $id")
        }
        return if (args.isEmpty()) template else String.format(locale, template, *args)
    }
}
